spring:
  application:
    name: UserAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key:
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days